# Generated by Django 2.2.16 on 2020-10-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20201012_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
